/*
 * This source file was generated by the Gradle 'init' task
 */
package com.passwordmanager;

import com.passwordmanager.utils.InitDB;
import com.passwordmanager.views.MainAppView;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {

    private Stage primaryStage;

    @Override
    public void start(Stage stage) {
        this.primaryStage = stage;
        MainAppView mainAppView = new MainAppView(primaryStage);
        Scene scene = mainAppView.getScene();
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public static void main(String[] args) {
        InitDB.initialize();
        launch(args);
    }
}
